### PR TITLE
Add demo data

### LINKED ISSUE #45: Init database with demo data
It should be possible to initialize the database for development and testing with demo data.

Data that should be added:
- [x] activated accounts
- [x] devices
- [x] device-availabilities 
- [ ] (optional) small network graph

### PR DESCRIPTION
**Pull request by michael-kamel**
Closes #56 
This is a base program for populating the DB. I suggest we decide on ways for doing this though.

To run it `gradle bootRun --args="--populatedb=true"`
 we can

1. Use a pre programmed script like the one provided here
2. Add data from flat files (we would have to find a way to take care of cross references)
3. Use arguments for deciding the number of data required ex. (--users=3 --devices=4 --availabilities=2) and populate information using a pool / library.

### CODE REVIEW

**Comment by chaoran-chen** [comment]
Approach 1 sounds simple and good enough for us in my opinion. Approach 3 seems too much since we are not developing a benchmarking framework. We would only need an option to activate and deactivate the creation of demo data.

**Comment by michael-kamel** [comment]
> Approach 1 sounds simple and good enough for us in my opinion. Approach 3 seems too much since we are not developing a benchmarking framework. We would only need an option to activate and deactivate the creation of demo data.

Approach 3 would allow us to import data directly from the fachteam. The option to import or not is there, I'll document this.

**Comment by michael-kamel** [comment]
If we are going to add nodes as well, I recommend we implement the functionalities for adding nodes first instead of hard coding it for the tests. Otherwise, this should be ready for merging.

**Review by chaoran-chen — COMMENTED** [review]
Hey, thanks for the PR! The code looks fine but could we maybe wait for a little? I am going to ask our chemists to create some mock data which you could then use instead.

"Mr." is not a title, we are more thinking of Prof. or Dr. ;)

**Comment by vordemann** [comment]
Is this PR still relevant? Some mock data has already been added by the Fachteam.

**Comment by chaoran-chen** [comment]
Yes, it's still relevant. I will export the data created by the Fachteam, then @michael-kamel, it would be nice if you can use them as mock data.

**Review by chaoran-chen — APPROVED** [review]
Great! Thank you!

(I made a small change and modified the email address of the demo person to avoid sending emails to @test.com at some point.)

**Pull request merged**
