### PR TITLE
Add linting support

### LINKED ISSUE #11: Linting
Consider using linting to increase readability and for a smooth code review process.

### PR DESCRIPTION
**Pull request by michael-kamel**
Fixes #11 
There are many options for formatting / linting and no go to standard solution.
I used a basic [Sun](https://checkstyle.sourceforge.io/sun_style.html) style checkstyle configuration in this pr. 
Maybe we can use something like SonarQube instead for managing overall quality?

- No tabs allowed
- Allowed length up to 100
- Disabled DesignForExtension(too defensive)
- Allow no doc for methods with up to 5 lines. 
- I ended up disabling the check for method docs as I found that is it a bit too restrictive for what we are doing. Furthermore, the goal of this is not to enforce docs, but to maintain a consistent style.
- Disabled FinalParameters (While is it intuitively a good practice to not modify params, it is too defensive. 
	This should be allowed but the developer should take responsibility to document any workarounds/hacks that utilize this)
- Ignored annotation magic numbers
- JavadocPackage(not worth stalling builds for)
- Disabled checks for test files(we probably need to refactor our tests anyway so no point in doing this right now)

Additional changes
- ignored line length checks for annotations
- Only check number of parameters for methods not constructors
- Allow public final field

Final Changes
- Extended line length to 120
- Removed lines with only an operator on them

### CODE REVIEW

**Comment by chaoran-chen** [comment]
I like the style :)

**Comment by vordemann** [comment]
Sun style checkstyle looks good

**Comment by vordemann** [comment]
Adjustments: no tabs, and line size amend

**Comment by benjiWdev** [comment]
looks good

**Review by chaoran-chen — APPROVED** [review]

**Pull request merged**
