### PR TITLE
Fetching wiki page by ID

### LINKED ISSUE #28: Single Wikipage Entry Endpoint
Provide an endpoint that returns a single wiki page by id
`GET /wiki?id=XYZ`

### PR DESCRIPTION
**Pull request by michael-kamel**
Closes #28

### CODE REVIEW

**Review by bieniusa — CHANGES_REQUESTED** [review]
Looks good! But can you please add a corresponding test case or refine the existing one(s)?

**Comment by michael-kamel** [comment]
> Looks good! But can you please add a corresponding test case or refine the existing one(s)?

We currently don't do any tests at the API level since most of the methods have little to no business logic and some things might be changed in the future on this specific level like endpoint names, payload contents, etc...

**Comment by chaoran-chen** [comment]
What do you think, @bieniusa?

Also, please rebase again ;)

**Comment by bieniusa** [comment]
The tests I had in mind are those: https://github.com/icebreaker-science/backend/blob/47c037b2d6ab68ddff965fd17721a4de3dc8b271/src/test/java/science/icebreaker/wiki/WikiControllerTest.java#L29

I believe this could be simplified with your API change.

**Comment by michael-kamel** [comment]
I modified the test but as I pointed out in #32 We need to do some refactoring to tests in general to avoid problems like this.

**Review by bieniusa — APPROVED** [review]

**Pull request merged**
